New algorithm for detecting X,Y shift on gravity
Finally found a property that I (think) I can use to detect when a
window will be offset in its X,Y. If a window has NorthWest gravity,
which windows may have explicitly or may have by default, it will be
offset, but the konsole windows with static gravity are not offset.

Signed-off-by: Blaine Gardner <blaine.gardner@suse.com>

diff --git a/window-layout b/window-layout
--- a/window-layout
+++ b/window-layout
@@ -1,16 +1,6 @@
 #!/usr/bin/env bash
 set -e
 
-# Most windows have their X,Y coordinates shifted by an amount equal to the
-# window decorations (titlebar, edges, etc.). There are some programs which
-# don't follow this rule.
-# This list should contain the name of the program as given by `ps -p PID`
-# separated by a single space each.
-DECORATION_EXCEPTIONS="konsole"
-# Programs known to have X,Y shift:
-# - chrome (only if the "Use system title bar and borders" is set)
-# - atom, pidgin, thunderbird, paprefs, pactl
-
 USAGE=$(cat << EOF
 Usage:
 $0 <save|load> [savename] -- save/load window layout with optional savename
@@ -43,8 +33,6 @@ save_layout () {
     # ID Desktop PID X Y Width Height Host? Title
     echo $window_info
     id="$(echo $window_info | awk '{print $1}')"
-    pid="$(echo $window_info | awk '{print $3}')"
-    process_name="$(ps -p $pid -o comm=)"
     title="$(echo $window_info | awk '{print substr($0, index($0, $9))}')"
 
     # Get desktop, x, y, width, and height info
@@ -55,14 +43,8 @@ save_layout () {
     height="$(echo $window_info | awk '{print $7}')"
 
     # Save info to a line in our save file
-    echo "$id $desktop $x $y $width $height $process_name '$title'" >> "${SAVEPATH}/${savename}"
+    echo "$id $desktop $x $y $width $height '$title'" >> "${SAVEPATH}/${savename}"
   done
-}
-
-contains () {
-  local list="$1"
-  local key="$2"
-  [[ "$list" =~ (^|[[:space:]])"$key"($|[[:space:]]) ]] && return 0 || return 1
 }
 
 load_layout () {
@@ -76,22 +58,24 @@ load_layout () {
     y="$(echo $window_info | cut --delimiter ' ' --fields 4)"
     width="$(echo $window_info | cut --delimiter ' ' --fields 5)"
     height="$(echo $window_info | cut --delimiter ' ' --fields 6)"
-    process_name="$(echo $window_info | cut --delimiter ' ' --fields 7)"
-    title="$(echo $window_info | awk '{print substr($0, index($0, $8))}')"
+    title="$(echo $window_info | awk '{print substr($0, index($0, $7))}')"
+
+    if ! xwininfo -id $id > /dev/null ; then
+      echo ""
+      echo "WARN: Error getting window properties. It might not exist. Continuing with next item."
+      continue
+    fi
 
     # Most programs need x,y adjusted by window decoration amounts.
-    # Not sure why this is. I can't find any property unique to these windows
-    # that suggests a different way to fix this other than this hard-coding.
-    # I've investigated the `xwininfo` of the window ID as well as the
-    # `xwininfo` of the parent window ID. Neither suggested a definite
-    # relationship between a property and whether the window needs x,y adjusted
-    if ! contains "$DECORATION_EXCEPTIONS" "$process_name" ; then
+    # The only relationship I can find is that windows with northwest gravity
+    # as reported by xprop (but not by xwininfo) are offset, whereas windows
+    # with static gravity are not. I haven't observed other gravities.
+    # Some windows (chrome) aren't set at all, and the default is northwest.
+    properties="$(xprop WM_NORMAL_HINTS -id $id)"
+    # ^ does not exist w/ chrome!?!?
+    if [[ ! "$properties" =~ "window gravity:" ]] || \
+       [[ "$properties" =~ "window gravity: NorthWest" ]] ; then
       # Get window decorations
-      if ! xprop _NET_FRAME_EXTENTS -id $id ; then
-        echo ""
-        echo "WARN: Error getting window properties. It might not exist. Continuing."
-        continue
-      fi
       decoration="$(xprop _NET_FRAME_EXTENTS -id $id | cut --delimiter '=' --fields 2 | tr --delete ' ')"
       decor_left="$(echo $decoration | cut --delimiter ',' --fields 1)"
       # decor_right="$(echo $decoration | cut --delimiter ',' --fields 2)"
